/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FooRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4322535741868599300L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FooRecord\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"COL1\",\"type\":\"int\"},{\"name\":\"COL2\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FooRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FooRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FooRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FooRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FooRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FooRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FooRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FooRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FooRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int COL1;
  private int COL2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FooRecord() {}

  /**
   * All-args constructor.
   * @param COL1 The new value for COL1
   * @param COL2 The new value for COL2
   */
  public FooRecord(java.lang.Integer COL1, java.lang.Integer COL2) {
    this.COL1 = COL1;
    this.COL2 = COL2;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return COL1;
    case 1: return COL2;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: COL1 = (java.lang.Integer)value$; break;
    case 1: COL2 = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'COL1' field.
   * @return The value of the 'COL1' field.
   */
  public int getCOL1() {
    return COL1;
  }


  /**
   * Sets the value of the 'COL1' field.
   * @param value the value to set.
   */
  public void setCOL1(int value) {
    this.COL1 = value;
  }

  /**
   * Gets the value of the 'COL2' field.
   * @return The value of the 'COL2' field.
   */
  public int getCOL2() {
    return COL2;
  }


  /**
   * Sets the value of the 'COL2' field.
   * @param value the value to set.
   */
  public void setCOL2(int value) {
    this.COL2 = value;
  }

  /**
   * Creates a new FooRecord RecordBuilder.
   * @return A new FooRecord RecordBuilder
   */
  public static example.avro.FooRecord.Builder newBuilder() {
    return new example.avro.FooRecord.Builder();
  }

  /**
   * Creates a new FooRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FooRecord RecordBuilder
   */
  public static example.avro.FooRecord.Builder newBuilder(example.avro.FooRecord.Builder other) {
    if (other == null) {
      return new example.avro.FooRecord.Builder();
    } else {
      return new example.avro.FooRecord.Builder(other);
    }
  }

  /**
   * Creates a new FooRecord RecordBuilder by copying an existing FooRecord instance.
   * @param other The existing instance to copy.
   * @return A new FooRecord RecordBuilder
   */
  public static example.avro.FooRecord.Builder newBuilder(example.avro.FooRecord other) {
    if (other == null) {
      return new example.avro.FooRecord.Builder();
    } else {
      return new example.avro.FooRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for FooRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FooRecord>
    implements org.apache.avro.data.RecordBuilder<FooRecord> {

    private int COL1;
    private int COL2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.FooRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.COL1)) {
        this.COL1 = data().deepCopy(fields()[0].schema(), other.COL1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.COL2)) {
        this.COL2 = data().deepCopy(fields()[1].schema(), other.COL2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing FooRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.FooRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.COL1)) {
        this.COL1 = data().deepCopy(fields()[0].schema(), other.COL1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.COL2)) {
        this.COL2 = data().deepCopy(fields()[1].schema(), other.COL2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'COL1' field.
      * @return The value.
      */
    public int getCOL1() {
      return COL1;
    }


    /**
      * Sets the value of the 'COL1' field.
      * @param value The value of 'COL1'.
      * @return This builder.
      */
    public example.avro.FooRecord.Builder setCOL1(int value) {
      validate(fields()[0], value);
      this.COL1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'COL1' field has been set.
      * @return True if the 'COL1' field has been set, false otherwise.
      */
    public boolean hasCOL1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'COL1' field.
      * @return This builder.
      */
    public example.avro.FooRecord.Builder clearCOL1() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'COL2' field.
      * @return The value.
      */
    public int getCOL2() {
      return COL2;
    }


    /**
      * Sets the value of the 'COL2' field.
      * @param value The value of 'COL2'.
      * @return This builder.
      */
    public example.avro.FooRecord.Builder setCOL2(int value) {
      validate(fields()[1], value);
      this.COL2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'COL2' field has been set.
      * @return True if the 'COL2' field has been set, false otherwise.
      */
    public boolean hasCOL2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'COL2' field.
      * @return This builder.
      */
    public example.avro.FooRecord.Builder clearCOL2() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FooRecord build() {
      try {
        FooRecord record = new FooRecord();
        record.COL1 = fieldSetFlags()[0] ? this.COL1 : (java.lang.Integer) defaultValue(fields()[0]);
        record.COL2 = fieldSetFlags()[1] ? this.COL2 : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FooRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<FooRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FooRecord>
    READER$ = (org.apache.avro.io.DatumReader<FooRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.COL1);

    out.writeInt(this.COL2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.COL1 = in.readInt();

      this.COL2 = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.COL1 = in.readInt();
          break;

        case 1:
          this.COL2 = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










