/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ReceiptRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4717507559455904259L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReceiptRecord\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"signature\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ReceiptRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReceiptRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReceiptRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReceiptRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReceiptRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReceiptRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReceiptRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReceiptRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReceiptRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence signature;
  private java.lang.CharSequence content;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReceiptRecord() {}

  /**
   * All-args constructor.
   * @param signature The new value for signature
   * @param content The new value for content
   */
  public ReceiptRecord(java.lang.CharSequence signature, java.lang.CharSequence content) {
    this.signature = signature;
    this.content = content;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return signature;
    case 1: return content;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: signature = (java.lang.CharSequence)value$; break;
    case 1: content = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'signature' field.
   * @return The value of the 'signature' field.
   */
  public java.lang.CharSequence getSignature() {
    return signature;
  }


  /**
   * Sets the value of the 'signature' field.
   * @param value the value to set.
   */
  public void setSignature(java.lang.CharSequence value) {
    this.signature = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Creates a new ReceiptRecord RecordBuilder.
   * @return A new ReceiptRecord RecordBuilder
   */
  public static example.avro.ReceiptRecord.Builder newBuilder() {
    return new example.avro.ReceiptRecord.Builder();
  }

  /**
   * Creates a new ReceiptRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReceiptRecord RecordBuilder
   */
  public static example.avro.ReceiptRecord.Builder newBuilder(example.avro.ReceiptRecord.Builder other) {
    if (other == null) {
      return new example.avro.ReceiptRecord.Builder();
    } else {
      return new example.avro.ReceiptRecord.Builder(other);
    }
  }

  /**
   * Creates a new ReceiptRecord RecordBuilder by copying an existing ReceiptRecord instance.
   * @param other The existing instance to copy.
   * @return A new ReceiptRecord RecordBuilder
   */
  public static example.avro.ReceiptRecord.Builder newBuilder(example.avro.ReceiptRecord other) {
    if (other == null) {
      return new example.avro.ReceiptRecord.Builder();
    } else {
      return new example.avro.ReceiptRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReceiptRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReceiptRecord>
    implements org.apache.avro.data.RecordBuilder<ReceiptRecord> {

    private java.lang.CharSequence signature;
    private java.lang.CharSequence content;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.ReceiptRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.signature)) {
        this.signature = data().deepCopy(fields()[0].schema(), other.signature);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ReceiptRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.ReceiptRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.signature)) {
        this.signature = data().deepCopy(fields()[0].schema(), other.signature);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'signature' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignature() {
      return signature;
    }


    /**
      * Sets the value of the 'signature' field.
      * @param value The value of 'signature'.
      * @return This builder.
      */
    public example.avro.ReceiptRecord.Builder setSignature(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.signature = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'signature' field has been set.
      * @return True if the 'signature' field has been set, false otherwise.
      */
    public boolean hasSignature() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'signature' field.
      * @return This builder.
      */
    public example.avro.ReceiptRecord.Builder clearSignature() {
      signature = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public example.avro.ReceiptRecord.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public example.avro.ReceiptRecord.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReceiptRecord build() {
      try {
        ReceiptRecord record = new ReceiptRecord();
        record.signature = fieldSetFlags()[0] ? this.signature : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReceiptRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReceiptRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReceiptRecord>
    READER$ = (org.apache.avro.io.DatumReader<ReceiptRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.signature);

    out.writeString(this.content);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.signature = in.readString(this.signature instanceof Utf8 ? (Utf8)this.signature : null);

      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.signature = in.readString(this.signature instanceof Utf8 ? (Utf8)this.signature : null);
          break;

        case 1:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










