apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-zookeeper-config
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-kafka-config
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "ter-zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://ter-broker:29092,PLAINTEXT_HOST://localhost:9092"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-schema-registry-config
data:
  SCHEMA_REGISTRY_HOST_NAME: "ter-schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "ter-zookeeper:2181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-kafka-connect-config
data:
  CONNECT_BOOTSTRAP_SERVERS: "ter-kafka:29092"
  CONNECT_REST_ADVERTISED_HOST_NAME: "ter-kafka-connect"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "ter-kafka-connect"
  CONNECT_CONFIG_STORAGE_TOPIC: "_ter-kafka-connect-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "_ter-kafka-connect-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "_ter-kafka-connect-status"
  CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://ter-schema-registry:8081"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://ter-schema-registry:8081"
  CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
  CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/,/connectors/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-ksqldb-config
data:
  KSQL_LISTENERS: "http://0.0.0.0:8088"
  KSQL_BOOTSTRAP_SERVERS: "ter-kafka:29092"
  KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
  KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  KSQL_KSQL_CONNECT_URL: "http://ter-kafka-connect:8083"
  KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://ter-schema-registry:8081"
  KSQL_KSQL_SERVICE_ID: "confluent_rmoff_01"
  KSQL_KSQL_HIDDEN_TOPICS: "^_.*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-postgres-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: it6g
  name: ter-postgrest-config
data:
  PGRST_DB_URI: "postgres://postgres:postgres@ter-postgres:5432/postgres"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "anon"